type: RasterDB
version: 1
ref:
  pixel_size: {x: 0.7, y: 0.6999999999991088}
  offset: {x: 596941.56, y: 5671674.1001}
  code: EPSG:32632
  proj4: +proj=utm +zone=32 +datum=WGS84 +units=m +no_defs
bands:
  1: {type: 1, wavelength: 408.5, fwhm: 4.4, title: band1}
  2: {type: 1, wavelength: 412.1, fwhm: 4.4, title: band2}
  3: {type: 1, wavelength: 415.7, fwhm: 4.4, title: band3}
  4: {type: 1, wavelength: 419.4, fwhm: 4.4, title: band4}
  5: {type: 1, wavelength: 423.0, fwhm: 4.4, title: band5}
  6: {type: 1, wavelength: 426.6, fwhm: 4.4, title: band6}
  7: {type: 1, wavelength: 430.2, fwhm: 4.4, title: band7}
  8: {type: 1, wavelength: 433.9, fwhm: 4.4, title: band8}
  9: {type: 1, wavelength: 437.5, fwhm: 4.4, title: band9}
  10: {type: 1, wavelength: 441.1, fwhm: 4.4, title: band10}
  11: {type: 1, wavelength: 444.7, fwhm: 4.4, title: band11}
  12: {type: 1, wavelength: 448.4, fwhm: 4.4, title: band12}
  13: {type: 1, wavelength: 452.0, fwhm: 4.4, title: band13}
  14: {type: 1, wavelength: 455.6, fwhm: 4.4, title: band14}
  15: {type: 1, wavelength: 459.3, fwhm: 4.4, title: band15}
  16: {type: 1, wavelength: 462.9, fwhm: 4.4, title: band16}
  17: {type: 1, wavelength: 466.5, fwhm: 4.4, title: band17}
  18: {type: 1, wavelength: 470.1, fwhm: 4.4, title: band18}
  19: {type: 1, wavelength: 473.8, fwhm: 4.4, title: band19}
  20: {type: 1, wavelength: 477.4, fwhm: 4.4, title: band20}
  21: {type: 1, wavelength: 481.0, fwhm: 4.4, title: band21}
  22: {type: 1, wavelength: 484.6, fwhm: 4.4, title: band22}
  23: {type: 1, wavelength: 488.3, fwhm: 4.4, title: band23}
  24: {type: 1, wavelength: 491.9, fwhm: 4.4, title: band24}
  25: {type: 1, wavelength: 495.5, fwhm: 4.4, title: band25}
  26: {type: 1, wavelength: 499.1, fwhm: 4.4, title: band26}
  27: {type: 1, wavelength: 502.8, fwhm: 4.4, title: band27}
  28: {type: 1, wavelength: 506.399, fwhm: 4.4, title: band28}
  29: {type: 1, wavelength: 510.0, fwhm: 4.4, title: band29}
  30: {type: 1, wavelength: 513.7, fwhm: 4.4, title: band30}
  31: {type: 1, wavelength: 517.3, fwhm: 4.4, title: band31}
  32: {type: 1, wavelength: 520.9, fwhm: 4.4, title: band32}
  33: {type: 1, wavelength: 524.5, fwhm: 4.4, title: band33}
  34: {type: 1, wavelength: 528.2, fwhm: 4.4, title: band34}
  35: {type: 1, wavelength: 531.8, fwhm: 4.4, title: band35}
  36: {type: 1, wavelength: 535.4, fwhm: 4.4, title: band36}
  37: {type: 1, wavelength: 539.0, fwhm: 4.4, title: band37}
  38: {type: 1, wavelength: 542.7, fwhm: 4.4, title: band38}
  39: {type: 1, wavelength: 546.3, fwhm: 4.4, title: band39}
  40: {type: 1, wavelength: 549.9, fwhm: 4.4, title: band40}
  41: {type: 1, wavelength: 553.5, fwhm: 4.4, title: band41}
  42: {type: 1, wavelength: 557.2, fwhm: 4.4, title: band42}
  43: {type: 1, wavelength: 560.8, fwhm: 4.4, title: band43}
  44: {type: 1, wavelength: 564.4, fwhm: 4.4, title: band44}
  45: {type: 1, wavelength: 568.1, fwhm: 4.4, title: band45}
  46: {type: 1, wavelength: 571.7, fwhm: 4.4, title: band46}
  47: {type: 1, wavelength: 575.3, fwhm: 4.4, title: band47}
  48: {type: 1, wavelength: 578.9, fwhm: 4.4, title: band48}
  49: {type: 1, wavelength: 582.6, fwhm: 4.4, title: band49}
  50: {type: 1, wavelength: 586.2, fwhm: 4.4, title: band50}
  51: {type: 1, wavelength: 589.8, fwhm: 4.4, title: band51}
  52: {type: 1, wavelength: 593.4, fwhm: 4.4, title: band52}
  53: {type: 1, wavelength: 597.1, fwhm: 4.4, title: band53}
  54: {type: 1, wavelength: 600.7, fwhm: 4.4, title: band54}
  55: {type: 1, wavelength: 604.3, fwhm: 4.4, title: band55}
  56: {type: 1, wavelength: 607.9, fwhm: 4.4, title: band56}
  57: {type: 1, wavelength: 611.6, fwhm: 4.4, title: band57}
  58: {type: 1, wavelength: 615.2, fwhm: 4.4, title: band58}
  59: {type: 1, wavelength: 618.8, fwhm: 4.4, title: band59}
  60: {type: 1, wavelength: 622.5, fwhm: 4.4, title: band60}
  61: {type: 1, wavelength: 626.1, fwhm: 4.4, title: band61}
  62: {type: 1, wavelength: 629.7, fwhm: 4.4, title: band62}
  63: {type: 1, wavelength: 633.3, fwhm: 4.4, title: band63}
  64: {type: 1, wavelength: 637.0, fwhm: 4.4, title: band64}
  65: {type: 1, wavelength: 640.6, fwhm: 4.4, title: band65}
  66: {type: 1, wavelength: 644.2, fwhm: 4.4, title: band66}
  67: {type: 1, wavelength: 647.8, fwhm: 4.4, title: band67}
  68: {type: 1, wavelength: 651.5, fwhm: 4.4, title: band68}
  69: {type: 1, wavelength: 655.1, fwhm: 4.4, title: band69}
  70: {type: 1, wavelength: 658.7, fwhm: 4.4, title: band70}
  71: {type: 1, wavelength: 662.4, fwhm: 4.4, title: band71}
  72: {type: 1, wavelength: 666.0, fwhm: 4.4, title: band72}
  73: {type: 1, wavelength: 669.6, fwhm: 4.4, title: band73}
  74: {type: 1, wavelength: 673.2, fwhm: 4.4, title: band74}
  75: {type: 1, wavelength: 676.9, fwhm: 4.4, title: band75}
  76: {type: 1, wavelength: 680.5, fwhm: 4.4, title: band76}
  77: {type: 1, wavelength: 684.1, fwhm: 4.4, title: band77}
  78: {type: 1, wavelength: 687.7, fwhm: 4.4, title: band78}
  79: {type: 1, wavelength: 691.4, fwhm: 4.4, title: band79}
  80: {type: 1, wavelength: 695.0, fwhm: 4.4, title: band80}
  81: {type: 1, wavelength: 698.6, fwhm: 4.4, title: band81}
  82: {type: 1, wavelength: 702.2, fwhm: 4.4, title: band82}
  83: {type: 1, wavelength: 705.9, fwhm: 4.4, title: band83}
  84: {type: 1, wavelength: 709.5, fwhm: 4.4, title: band84}
  85: {type: 1, wavelength: 713.1, fwhm: 4.4, title: band85}
  86: {type: 1, wavelength: 716.8, fwhm: 4.4, title: band86}
  87: {type: 1, wavelength: 720.4, fwhm: 4.4, title: band87}
  88: {type: 1, wavelength: 724.0, fwhm: 4.4, title: band88}
  89: {type: 1, wavelength: 727.6, fwhm: 4.4, title: band89}
  90: {type: 1, wavelength: 731.3, fwhm: 4.4, title: band90}
  91: {type: 1, wavelength: 734.9, fwhm: 4.4, title: band91}
  92: {type: 1, wavelength: 738.5, fwhm: 4.4, title: band92}
  93: {type: 1, wavelength: 742.1, fwhm: 4.4, title: band93}
  94: {type: 1, wavelength: 745.8, fwhm: 4.4, title: band94}
  95: {type: 1, wavelength: 749.4, fwhm: 4.4, title: band95}
  96: {type: 1, wavelength: 753.0, fwhm: 4.4, title: band96}
  97: {type: 1, wavelength: 756.6, fwhm: 4.4, title: band97}
  98: {type: 1, wavelength: 760.3, fwhm: 4.4, title: band98}
  99: {type: 1, wavelength: 763.9, fwhm: 4.4, title: band99}
  100: {type: 1, wavelength: 767.5, fwhm: 4.4, title: band100}
  101: {type: 1, wavelength: 771.1, fwhm: 4.4, title: band101}
  102: {type: 1, wavelength: 774.8, fwhm: 4.4, title: band102}
  103: {type: 1, wavelength: 778.4, fwhm: 4.4, title: band103}
  104: {type: 1, wavelength: 782.0, fwhm: 4.4, title: band104}
  105: {type: 1, wavelength: 785.7, fwhm: 4.4, title: band105}
  106: {type: 1, wavelength: 789.3, fwhm: 4.4, title: band106}
  107: {type: 1, wavelength: 792.9, fwhm: 4.4, title: band107}
  108: {type: 1, wavelength: 796.5, fwhm: 4.4, title: band108}
  109: {type: 1, wavelength: 800.2, fwhm: 4.4, title: band109}
  110: {type: 1, wavelength: 803.8, fwhm: 4.4, title: band110}
  111: {type: 1, wavelength: 807.4, fwhm: 4.4, title: band111}
  112: {type: 1, wavelength: 811.0, fwhm: 4.4, title: band112}
  113: {type: 1, wavelength: 814.7, fwhm: 4.4, title: band113}
  114: {type: 1, wavelength: 818.3, fwhm: 4.4, title: band114}
  115: {type: 1, wavelength: 821.9, fwhm: 4.4, title: band115}
  116: {type: 1, wavelength: 825.6, fwhm: 4.4, title: band116}
  117: {type: 1, wavelength: 829.2, fwhm: 4.4, title: band117}
  118: {type: 1, wavelength: 832.8, fwhm: 4.4, title: band118}
  119: {type: 1, wavelength: 836.4, fwhm: 4.4, title: band119}
  120: {type: 1, wavelength: 840.1, fwhm: 4.4, title: band120}
  121: {type: 1, wavelength: 843.7, fwhm: 4.4, title: band121}
  122: {type: 1, wavelength: 847.3, fwhm: 4.4, title: band122}
  123: {type: 1, wavelength: 850.9, fwhm: 4.4, title: band123}
  124: {type: 1, wavelength: 854.6, fwhm: 4.4, title: band124}
  125: {type: 1, wavelength: 858.2, fwhm: 4.4, title: band125}
  126: {type: 1, wavelength: 861.8, fwhm: 4.4, title: band126}
  127: {type: 1, wavelength: 865.4, fwhm: 4.4, title: band127}
  128: {type: 1, wavelength: 869.1, fwhm: 4.4, title: band128}
  129: {type: 1, wavelength: 872.7, fwhm: 4.4, title: band129}
  130: {type: 1, wavelength: 876.3, fwhm: 4.4, title: band130}
  131: {type: 1, wavelength: 880.0, fwhm: 4.4, title: band131}
  132: {type: 1, wavelength: 883.6, fwhm: 4.4, title: band132}
  133: {type: 1, wavelength: 887.2, fwhm: 4.4, title: band133}
  134: {type: 1, wavelength: 890.8, fwhm: 4.4, title: band134}
  135: {type: 1, wavelength: 894.5, fwhm: 4.4, title: band135}
  136: {type: 1, wavelength: 898.1, fwhm: 4.4, title: band136}
  137: {type: 1, wavelength: 901.7, fwhm: 4.4, title: band137}
  138: {type: 1, wavelength: 905.3, fwhm: 4.4, title: band138}
  139: {type: 1, wavelength: 909.0, fwhm: 4.4, title: band139}
  140: {type: 1, wavelength: 912.6, fwhm: 4.4, title: band140}
  141: {type: 1, wavelength: 916.2, fwhm: 4.4, title: band141}
  142: {type: 1, wavelength: 919.8, fwhm: 4.4, title: band142}
  143: {type: 1, wavelength: 923.5, fwhm: 4.4, title: band143}
  144: {type: 1, wavelength: 927.1, fwhm: 4.4, title: band144}
  145: {type: 1, wavelength: 930.7, fwhm: 4.4, title: band145}
  146: {type: 1, wavelength: 934.4, fwhm: 4.4, title: band146}
  147: {type: 1, wavelength: 938.0, fwhm: 4.4, title: band147}
  148: {type: 1, wavelength: 941.6, fwhm: 4.4, title: band148}
  149: {type: 1, wavelength: 945.2, fwhm: 4.4, title: band149}
  150: {type: 1, wavelength: 948.9, fwhm: 4.4, title: band150}
  151: {type: 1, wavelength: 952.5, fwhm: 4.4, title: band151}
  152: {type: 1, wavelength: 956.1, fwhm: 4.4, title: band152}
  153: {type: 1, wavelength: 959.7, fwhm: 4.4, title: band153}
  154: {type: 1, wavelength: 963.4, fwhm: 4.4, title: band154}
  155: {type: 1, wavelength: 967.0, fwhm: 4.4, title: band155}
  156: {type: 1, wavelength: 970.6, fwhm: 4.4, title: band156}
  157: {type: 1, wavelength: 974.2, fwhm: 4.4, title: band157}
  158: {type: 1, wavelength: 977.9, fwhm: 4.4, title: band158}
  159: {type: 1, wavelength: 981.5, fwhm: 4.4, title: band159}
  160: {type: 1, wavelength: 985.1, fwhm: 4.4, title: band160}
associated: {}
acl: []
acl_mod: []
tags: []
local_extent: {xmin: 0, ymin: 0, xmax: 689, ymax: 208}
storage_type: TileStorage
tile_pixel_len: 256
